const currencyMapping = {
    AED: {
        country: "United Arab Emirates",
        currency: "UAE Dirham",
        flagId: "AE",
    },
    AFN: { country: "Afghanistan", currency: "Afghan Afghani", flagId: "AF" },
    ALL: { country: "Albania", currency: "Albanian Lek", flagId: "AL" },
    AMD: { country: "Armenia", currency: "Armenian Dram", flagId: "AM" },
    ANG: {
        country: "Netherlands Antilles",
        currency: "Netherlands Antillean Guilder",
        flagId: "CW",
    },
    AOA: { country: "Angola", currency: "Angolan Kwanza", flagId: "AO" },
    ARS: { country: "Argentina", currency: "Argentine Peso", flagId: "AR" },
    AUD: { country: "Australia", currency: "Australian Dollar", flagId: "AU" },
    AWG: { country: "Aruba", currency: "Aruban Florin", flagId: "AW" },
    AZN: { country: "Azerbaijan", currency: "Azerbaijani Manat", flagId: "AZ" },
    BAM: {
        country: "Bosnia and Herzegovina",
        currency: "Bosnia-Herzegovina Convertible Mark",
        flagId: "BA",
    },
    BBD: { country: "Barbados", currency: "Barbadian Dollar", flagId: "BB" },
    BDT: { country: "Bangladesh", currency: "Bangladeshi Taka", flagId: "BD" },
    BGN: { country: "Bulgaria", currency: "Bulgarian Lev", flagId: "BG" },
    BHD: { country: "Bahrain", currency: "Bahraini Dinar", flagId: "BH" },
    BIF: { country: "Burundi", currency: "Burundian Franc", flagId: "BI" },
    BMD: { country: "Bermuda", currency: "Bermudian Dollar", flagId: "BM" },
    BND: { country: "Brunei", currency: "Brunei Dollar", flagId: "BN" },
    BOB: { country: "Bolivia", currency: "Bolivian Boliviano", flagId: "BO" },
    BRL: { country: "Brazil", currency: "Brazilian Real", flagId: "BR" },
    BSD: { country: "Bahamas", currency: "Bahamian Dollar", flagId: "BS" },
    BTN: { country: "Bhutan", currency: "Bhutanese Ngultrum", flagId: "BT" },
    BWP: { country: "Botswana", currency: "Botswanan Pula", flagId: "BW" },
    BYN: { country: "Belarus", currency: "Belarusian Ruble", flagId: "BY" },
    BZD: { country: "Belize", currency: "Belize Dollar", flagId: "BZ" },
    CAD: { country: "Canada", currency: "Canadian Dollar", flagId: "CA" },
    CDF: {
        country: "Democratic Republic of the Congo",
        currency: "Congolese Franc",
        flagId: "CD",
    },
    CHF: { country: "Switzerland", currency: "Swiss Franc", flagId: "CH" },
    CLP: { country: "Chile", currency: "Chilean Peso", flagId: "CL" },
    CNY: { country: "China", currency: "Chinese Yuan", flagId: "CN" },
    COP: { country: "Colombia", currency: "Colombian Peso", flagId: "CO" },
    CRC: { country: "Costa Rica", currency: "Costa Rican Colón", flagId: "CR" },
    CUP: { country: "Cuba", currency: "Cuban Peso", flagId: "CU" },
    CVE: {
        country: "Cape Verde",
        currency: "Cape Verdean Escudo",
        flagId: "CV",
    },
    CZK: { country: "Czech Republic", currency: "Czech Koruna", flagId: "CZ" },
    DJF: { country: "Djibouti", currency: "Djiboutian Franc", flagId: "DJ" },
    DKK: { country: "Denmark", currency: "Danish Krone", flagId: "DK" },
    DOP: {
        country: "Dominican Republic",
        currency: "Dominican Peso",
        flagId: "DO",
    },
    DZD: { country: "Algeria", currency: "Algerian Dinar", flagId: "DZ" },
    EGP: { country: "Egypt", currency: "Egyptian Pound", flagId: "EG" },
    ERN: { country: "Eritrea", currency: "Eritrean Nakfa", flagId: "ER" },
    ETB: { country: "Ethiopia", currency: "Ethiopian Birr", flagId: "ET" },
    EUR: { country: "European Union", currency: "Euro", flagId: "EU" },
    FJD: { country: "Fiji", currency: "Fijian Dollar", flagId: "FJ" },
    FKP: {
        country: "Falkland Islands",
        currency: "Falkland Islands Pound",
        flagId: "FK",
    },
    GBP: { country: "United Kingdom", currency: "British Pound", flagId: "GB" },
    GEL: { country: "Georgia", currency: "Georgian Lari", flagId: "GE" },
    GHS: { country: "Ghana", currency: "Ghanaian Cedi", flagId: "GH" },
    GIP: { country: "Gibraltar", currency: "Gibraltar Pound", flagId: "GI" },
    GMD: { country: "Gambia", currency: "Gambian Dalasi", flagId: "GM" },
    GNF: { country: "Guinea", currency: "Guinean Franc", flagId: "GN" },
    GTQ: { country: "Guatemala", currency: "Guatemalan Quetzal", flagId: "GT" },
    GYD: { country: "Guyana", currency: "Guyanese Dollar", flagId: "GY" },
    HKD: { country: "Hong Kong", currency: "Hong Kong Dollar", flagId: "HK" },
    HNL: { country: "Honduras", currency: "Honduran Lempira", flagId: "HN" },
    HRK: { country: "Croatia", currency: "Croatian Kuna", flagId: "HR" },
    HTG: { country: "Haiti", currency: "Haitian Gourde", flagId: "HT" },
    HUF: { country: "Hungary", currency: "Hungarian Forint", flagId: "HU" },
    IDR: { country: "Indonesia", currency: "Indonesian Rupiah", flagId: "ID" },
    ILS: { country: "Israel", currency: "Israeli New Shekel", flagId: "IL" },
    INR: { country: "India", currency: "Indian Rupee", flagId: "IN" },
    IQD: { country: "Iraq", currency: "Iraqi Dinar", flagId: "IQ" },
    IRR: { country: "Iran", currency: "Iranian Rial", flagId: "IR" },
    ISK: { country: "Iceland", currency: "Icelandic Króna", flagId: "IS" },
    JMD: { country: "Jamaica", currency: "Jamaican Dollar", flagId: "JM" },
    JOD: { country: "Jordan", currency: "Jordanian Dinar", flagId: "JO" },
    JPY: { country: "Japan", currency: "Japanese Yen", flagId: "JP" },
    KES: { country: "Kenya", currency: "Kenyan Shilling", flagId: "KE" },
    KGS: { country: "Kyrgyzstan", currency: "Kyrgyzstani Som", flagId: "KG" },
    KHR: { country: "Cambodia", currency: "Cambodian Riel", flagId: "KH" },
    KMF: { country: "Comoros", currency: "Comorian Franc", flagId: "KM" },
    KRW: { country: "South Korea", currency: "South Korean Won", flagId: "KR" },
    KWD: { country: "Kuwait", currency: "Kuwaiti Dinar", flagId: "KW" },
    KYD: {
        country: "Cayman Islands",
        currency: "Cayman Islands Dollar",
        flagId: "KY",
    },
    KZT: { country: "Kazakhstan", currency: "Kazakhstani Tenge", flagId: "KZ" },
    LAK: { country: "Laos", currency: "Laotian Kip", flagId: "LA" },
    LBP: { country: "Lebanon", currency: "Lebanese Pound", flagId: "LB" },
    LKR: { country: "Sri Lanka", currency: "Sri Lankan Rupee", flagId: "LK" },

    LRD: { country: "Liberia", currency: "Liberian Dollar", flagId: "LR" },
    LSL: { country: "Lesotho", currency: "Lesotho Loti", flagId: "LS" },
    LYD: { country: "Libya", currency: "Libyan Dinar", flagId: "LY" },
    MAD: { country: "Morocco", currency: "Moroccan Dirham", flagId: "MA" },
    MDL: { country: "Moldova", currency: "Moldovan Leu", flagId: "MD" },
    MGA: { country: "Madagascar", currency: "Malagasy Ariary", flagId: "MG" },
    MKD: {
        country: "North Macedonia",
        currency: "Macedonian Denar",
        flagId: "MK",
    },
    MMK: { country: "Myanmar", currency: "Myanmar Kyat", flagId: "MM" },
    MNT: { country: "Mongolia", currency: "Mongolian Tugrik", flagId: "MN" },
    MOP: { country: "Macau", currency: "Macanese Pataca", flagId: "MO" },
    MRU: {
        country: "Mauritania",
        currency: "Mauritanian Ouguiya",
        flagId: "MR",
    },
    MUR: { country: "Mauritius", currency: "Mauritian Rupee", flagId: "MU" },
    MVR: { country: "Maldives", currency: "Maldivian Rufiyaa", flagId: "MV" },
    MWK: { country: "Malawi", currency: "Malawian Kwacha", flagId: "MW" },
    MXN: { country: "Mexico", currency: "Mexican Peso", flagId: "MX" },
    MYR: { country: "Malaysia", currency: "Malaysian Ringgit", flagId: "MY" },
    MZN: {
        country: "Mozambique",
        currency: "Mozambican Metical",
        flagId: "MZ",
    },
    NAD: { country: "Namibia", currency: "Namibian Dollar", flagId: "NA" },
    NGN: { country: "Nigeria", currency: "Nigerian Naira", flagId: "NG" },
    NIO: { country: "Nicaragua", currency: "Nicaraguan Córdoba", flagId: "NI" },
    NOK: { country: "Norway", currency: "Norwegian Krone", flagId: "NO" },
    NPR: { country: "Nepal", currency: "Nepalese Rupee", flagId: "NP" },
    NZD: {
        country: "New Zealand",
        currency: "New Zealand Dollar",
        flagId: "NZ",
    },
    OMR: { country: "Oman", currency: "Omani Rial", flagId: "OM" },
    PAB: { country: "Panama", currency: "Panamanian Balboa", flagId: "PA" },
    PEN: { country: "Peru", currency: "Peruvian Sol", flagId: "PE" },
    PGK: {
        country: "Papua New Guinea",
        currency: "Papua New Guinean Kina",
        flagId: "PG",
    },
    PHP: { country: "Philippines", currency: "Philippine Peso", flagId: "PH" },
    PKR: { country: "Pakistan", currency: "Pakistani Rupee", flagId: "PK" },
    PLN: { country: "Poland", currency: "Polish Zloty", flagId: "PL" },
    PYG: { country: "Paraguay", currency: "Paraguayan Guarani", flagId: "PY" },
    QAR: { country: "Qatar", currency: "Qatari Riyal", flagId: "QA" },
    RON: { country: "Romania", currency: "Romanian Leu", flagId: "RO" },
    RSD: { country: "Serbia", currency: "Serbian Dinar", flagId: "RS" },
    RUB: { country: "Russia", currency: "Russian Ruble", flagId: "RU" },
    RWF: { country: "Rwanda", currency: "Rwandan Franc", flagId: "RW" },
    SAR: { country: "Saudi Arabia", currency: "Saudi Riyal", flagId: "SA" },
    SBD: {
        country: "Solomon Islands",
        currency: "Solomon Islands Dollar",
        flagId: "SB",
    },
    SCR: { country: "Seychelles", currency: "Seychellois Rupee", flagId: "SC" },
    SDG: { country: "Sudan", currency: "Sudanese Pound", flagId: "SD" },
    SEK: { country: "Sweden", currency: "Swedish Krona", flagId: "SE" },
    SGD: { country: "Singapore", currency: "Singapore Dollar", flagId: "SG" },
    SHP: {
        country: "Saint Helena",
        currency: "Saint Helena Pound",
        flagId: "SH",
    },
    SLE: {
        country: "Sierra Leone",
        currency: "Sierra Leonean Leone",
        flagId: "SL",
    },
    SLL: {
        country: "Sierra Leone (Old)",
        currency: "Sierra Leonean Leone",
        flagId: "SL",
    },
    SOS: { country: "Somalia", currency: "Somali Shilling", flagId: "SO" },
    SRD: { country: "Suriname", currency: "Surinamese Dollar", flagId: "SR" },
    SSP: {
        country: "South Sudan",
        currency: "South Sudanese Pound",
        flagId: "SS",
    },
    STN: {
        country: "São Tomé and Príncipe",
        currency: "São Tomé and Príncipe Dobra",
        flagId: "ST",
    },
    SYP: { country: "Syria", currency: "Syrian Pound", flagId: "SY" },
    SZL: { country: "Eswatini", currency: "Swazi Lilangeni", flagId: "SZ" },
    THB: { country: "Thailand", currency: "Thai Baht", flagId: "TH" },
    TJS: {
        country: "Tajikistan",
        currency: "Tajikistani Somoni",
        flagId: "TJ",
    },
    TMT: {
        country: "Turkmenistan",
        currency: "Turkmenistani Manat",
        flagId: "TM",
    },
    TND: { country: "Tunisia", currency: "Tunisian Dinar", flagId: "TN" },
    TOP: { country: "Tonga", currency: "Tongan Paʻanga", flagId: "TO" },
    TRY: { country: "Turkey", currency: "Turkish Lira", flagId: "TR" },
    TTD: {
        country: "Trinidad and Tobago",
        currency: "Trinidad and Tobago Dollar",
        flagId: "TT",
    },
    TWD: { country: "Taiwan", currency: "New Taiwan Dollar", flagId: "TW" },
    TZS: { country: "Tanzania", currency: "Tanzanian Shilling", flagId: "TZ" },
    UAH: { country: "Ukraine", currency: "Ukrainian Hryvnia", flagId: "UA" },
    UGX: { country: "Uganda", currency: "Ugandan Shilling", flagId: "UG" },
    USD: { country: "United States", currency: "US Dollar", flagId: "US" },
    UYU: { country: "Uruguay", currency: "Uruguayan Peso", flagId: "UY" },
    UZS: { country: "Uzbekistan", currency: "Uzbekistani Som", flagId: "UZ" },
    VES: { country: "Venezuela", currency: "Venezuelan Bolívar", flagId: "VE" },
    VND: { country: "Vietnam", currency: "Vietnamese Dong", flagId: "VN" },
    VUV: { country: "Vanuatu", currency: "Vanuatu Vatu", flagId: "VU" },
    WST: { country: "Samoa", currency: "Samoan Tala", flagId: "WS" },
    XAF: {
        country: "Central African States",
        currency: "CFA Franc BEAC",
        flagId: "CM",
    },
    XCD: {
        country: "Eastern Caribbean",
        currency: "East Caribbean Dollar",
        flagId: "AG",
    },
    XDR: { country: "IMF", currency: "Special Drawing Rights", flagId: "UN" },
    XOF: {
        country: "West African States",
        currency: "CFA Franc BCEAO",
        flagId: "CI",
    },
    XPF: { country: "French Polynesia", currency: "CFP Franc", flagId: "PF" },
    YER: { country: "Yemen", currency: "Yemeni Rial", flagId: "YE" },
    ZAR: {
        country: "South Africa",
        currency: "South African Rand",
        flagId: "ZA",
    },
    ZMW: { country: "Zambia", currency: "Zambian Kwacha", flagId: "ZM" },
    ZWL: { country: "Zimbabwe", currency: "Zimbabwean Dollar", flagId: "ZW" },
};

export default currencyMapping;
